# BetterEnd Master config file
# WORLD OPTIONS ARE FOUND IN WORLD CONFIGS!
# DO NOT ATTEMPT TO SET WORLD CONFIG OPTIONS IN THIS FILE!

# A hood classic, do not change this value!
config-version: 1

# Update Checker settings
update-checker:
  # Enable/disable the update checker.
  enable: true
  # The frequency (in seconds) to check for updates (21600 = 6 hours)
  frequency: 21600

# The language in which to display plugin messages
lang: en_us

# Enables/disables generation of custom trees in all worlds
big-trees-everywhere: false

# How much longer should it take to grow a big tree?
tree-sapling-growth-modifier: 8

# Whether to use parallel generation
parallel: true

# Whether to generate Vanilla End Cities. It is not recommended to enable this.
generate-end-cities: false

# Enable/disable debug mode
debug: false

# How often to save population data. This is done asynchronously, so it has little to no performance impact.
data-save: PT30M

# Whether to enable advancements (premium only)
advancements: true